apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-disk
  labels:
    name: backup-disk
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/projects/backup"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi