apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-disk
  labels:
    name: upload-disk
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/projects/upload"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: upload-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi