apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-accessibility
  labels:
    helloworld-accessibility: deployment
  annotations:
    description: Defines how to deploy helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: helloworld-accessibility
      labels:
        app: helloworld
        helloworld-accessibility: pod
    spec:
      containers:
        - name: helloworld
          image: helloworld:3
          ports:
            - containerPort: 4004
              name: "jvm-debug"
            - containerPort: 8080
              name: "running-port"
          env:
            - name: ENABLE_DEBUG
              value: "true"
            - name: SIMULATE_LONGER_STARTUP
              value: "true"
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            runAsUser: 999
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-accessibility
  labels:
    helloworld-accessibility: service
  annotations:
    description: Exposes hello world
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      nodePort: 31113
      targetPort: 8080
      protocol: TCP