apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-helloworld-accessibility
  labels:
    deploy-helloworld-accessibility: deployment
  annotations:
    description: Defines how to deploy helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: deploy-helloworld-accessibility
      labels:
        app: helloworld
        deploy-helloworld-accessibility: pod
    spec:
      serviceAccountName: custom-service-account
      containers:
        - name: helloworld
          image: helloworld:3
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            runAsUser: 999
---
kind: Service
apiVersion: v1
metadata:
  name: deploy-helloworld-accessibility
  labels:
    deploy-helloworld-accessibility: service
  annotations:
    description: Exposes hello world
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      nodePort: 30113
      targetPort: 8080
      protocol: TCP