apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-disruption
  labels:
    deploy-helloworld-disruption: deployment
  annotations:
    description: Defines how to deploy helloworld
spec:
  selector:
    matchLabels:
      app: helloworld-disruption
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      name: helloworld-disruption
      labels:
        app: helloworld-disruption
        deploy-helloworld-disruption: pod
    spec:
      containers:
        - name: helloworld
          image: helloworld:1
          ports:
            - containerPort: 8080
              name: "running-port"
#          terminationMessagePolicy: FallbackToLogsOnError
#          terminationMessagePath: "/tmp/custom-termination-log.log"
          env:
            - name: SIMULATE_LONGER_STARTUP
              value: "false"
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
              limits:
                memory: 512Mi
              requests:
                memory: 128Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 30
            periodSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 3
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-disruption
  labels:
    deploy-helloworld-disruption: service
  annotations:
    description: Exposes hello world application
spec:
  type: NodePort
  selector:
    app: helloworld-disruption
  ports:
    - port: 8080
      nodePort: 30005
      targetPort: 8080
      protocol: TCP
---