apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-helloworld
  labels:
    deploy-helloworld: deployment
  annotations:
    description: Defines how to deploy helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      name: deploy-helloworld
      labels:
        app: helloworld
        deploy-helloworld: pod
    spec:
      serviceAccountName: custom-service-account
      containers:
        - name: helloworld
          image: helloworld:3
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          readinessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 40
            timeoutSeconds: 3
            periodSeconds: 2
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  name: deploy-helloworld
  labels:
    deploy-helloworld: deployment
  annotations:
    description: Exposes hello world
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      nodePort: 31114
      targetPort: 8080
      protocol: TCP
---