apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-withaccount
  labels:
    helloworld-withaccount: deployment
  annotations:
    description: Defines how to deploy helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: helloworld-withaccount
      labels:
        app: helloworld
        helloworld-withaccount: pod
    spec:
      serviceAccountName: helloworld-service-account
      containers:
        - name: helloworld
          image: helloworld:1
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld-withaccount
  labels:
    helloworld-withaccount: service
  annotations:
    description: Exposes hello world
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      nodePort: 31112
      targetPort: 8080
      protocol: TCP
---