kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager
  namespace: dev
rules:
  - apiGroups: [ extensions, apps ]
    resources: [ deployments ]
    verbs: [ get, list ]